const { Schema, model } = require('mongoose');

const ClientesSchema = Schema({
    rubro: { type: String },
    nombre: { type: String },
    telefono: { type: String },
    email: { type: String },
    direccion: { type: String },
    empresa: { type: String },
    banco1: { type: String },
    cbu1: { type: String },
    cuentaCorriente1: { type: String },
    banco2: { type: String },
    cbu2: { type: String },
    cuentaCorriente2: { type: String },
    banco3: { type: String },
    cbu3: { type: String },
    cuentaCorriente3: { type: String },
    billeteraVirtual: { type: String },
    cvu: { type: String },
    cuit: { type: String },
    organismo: { type: String },
    provincia: { type: String },
    legajo: { type: String },
    situcion: { type: String },
    tramite: { type: String },
    pago: { type: Number, enum: [0, 1], default: 1 },
    usuarios1:{ type: String },
    pass1:{ type: String },
    usuarios2:{ type: String },
    pass2:{ type: String },
    usuarios3:{ type: String },
    pass3:{ type: String },
    usuarios4:{ type: String },
    pass4:{ type: String },
    usuarios5:{ type: String },
    pass5:{ type: String },
    servicioInternet:{ type: String },
    ubicacionCarpeta:{ type: String },
    servidor:{ type: String },
    estado: { type: String }
});

module.exports = model("Cliente", ClientesSchema, "Clientes");
